server:
  port: 8086
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/insurifyd
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: authentication-service

  cloud:
    compatibility-verifier:
      enabled: false
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 692492348685-qpv81o821qgrrobknsffo375288t4hea.apps.googleusercontent.com
#            clientSecret: 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

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka
